config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'

  #get '/about' => 'posts#about'

  resources :posts do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title,   presence:true,
                        length:{minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name:"mike", password:"1234", only: [:destroy]

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)

        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end

    private
        def comment_params
        params.require(:comment).permit(:username, :body)
        
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    http_basic_authenticate_with name:"mike", password:"1234", except: [:index, :show]

    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        #render plain: params[:post].inspect

        @post = Post.new(post_params)
        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end

    private
        def post_params
            params.require(:post).permit(:title, :body)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h1 class="title">Comments</h1>

<% if @post.comments.count < 1 %>
<p>Empty Comment</p>
<% else %>
    <% @post.comments.each do |comment| %>
        <div class="card">
            <div class="card-content">
                <p>
                    <strong><%= comment.username %> </strong>: <%= comment.body%>
                    <span>
                        <%= link_to "",[comment.post, comment],
                                                method: :delete,
                                                data: {confirm: 'Are you sure ?'},
                                                :class => 'delete' %>
                    </span>
                </p>
            </div>
        </div>
    <% end %>
<% end %>

<hr>

app/views/comments/_form.html.erb
<h1 class="title">Add Comment</h1>

<%= form_for ([@post, @post.comments.build]) do |f| %>

    <div class="field">
        <label><%= f.label :username, :class => 'label' %></label>
        <div class="control">
            <%= f.text_field :username, :class => 'input' %>
        </div>
    </div>

    <div class="field">
        <label<%= f.label :body, :class => 'label' %></label>
        <div class="control">
            <%= f.text_area :body, rows: 4, :class => 'textarea'  %>
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <%= f.submit ({:class => 'button is-primary'}) %>
        </div>
    </div>
    <p>
        
    </p>    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.0/css/bulma.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <section class="section">
    <div class="container">
      <nav class="level">
        <p class="level-item has-text-centered">
          <%= link_to "Home", home_path%>
        </p>
        <p class="level-item has-text-centered">
          <a class="link is-info">Menu</a>
        </p>
        <p class="level-item has-text-centered">
          <img src="http://bulma.io/images/bulma-type.png" alt="" style="height: 30px;">
        </p>
        <p class="level-item has-text-centered">
          <a class="link is-info">Reservations</a>
        </p>
        <p class="level-item has-text-centered">
          <%= link_to "Create Post", new_post_path%>
        </p>
      </nav>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
    
  </section>
  </body>
</html>

app/views/posts/about.html.erb
<h1>About</h1>

app/views/posts/edit.html.erb
<h1 class="title">Edit Post</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |err| %>
            <div class="notification is-danger"> <%= err %> </div>
        <% end %>
    <% end %>

    <div class="field">
        <label><%= f.label :title, :class => 'label' %></label>
        <div class="control">
            <%= f.text_field :title, :class => 'input' %>
        </div>
    </div>

    <div class="field">
        <label<%= f.label :body, :class => 'label' %></label>
        <div class="control">
            <%= f.text_area :body, rows: 4, :class => 'textarea'  %>
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <%= f.submit ({:class => 'button is-primary'}) %>
        </div>
    </div>
    <p>
        
    </p>    
<% end %>

app/views/posts/index.html.erb
<h1 class="title">Posts</h1>

<% if @posts.count < 1 %>
<p>Empty Post</p>
<% else %>
    <% @posts.each do |post| %>
        <div class="card">
            <div class="card-content">
                <p class="title">
                    "<%= post.body %>"
                </p>
                <p class="subtitle is-capitalized">
                    <%= post.title %>
                </p>
            </div>
            <footer class="card-footer">
                <p class="card-footer-item">
                    <span>
                        <%= link_to "Read More", post_path(post)%>
                    </span>
                </p>
            </footer>
        </div>
        <br>
    <% end %>
<% end %>

app/views/posts/new.html.erb
<h1 class="title">Add Post</h1>

<%= form_for :post, url: posts_path do |f| %>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |err| %>
            <div class="notification is-danger"> <%= err %> </div>
        <% end %>
    <% end %>

    <div class="field">
        <label><%= f.label :title, :class => 'label' %></label>
        <div class="control">
            <%= f.text_field :title, :class => 'input' %>
        </div>
    </div>

    <div class="field">
        <label<%= f.label :body, :class => 'label' %></label>
        <div class="control">
            <%= f.text_area :body, rows: 4, :class => 'textarea'  %>
        </div>
    </div>
    
    <div class="field">
        <div class="control">
            <%= f.submit ({:class => 'button is-primary'}) %>
        </div>
    </div>
    <p>
        
    </p>    
<% end %>

app/views/posts/show.html.erb
<h1 class="title"> Post : </h1>

<div class="card">
    <div class="card-content">
        <p class="title">
            "<%= @post.body %>"
        </p>
        <p class="subtitle">
            <%= @post.title %>
        </p>
    </div>
    <footer class="card-footer">
        <p class="card-footer-item">
            <span>
                <%= link_to "Edit", edit_post_path(@post), :class => 'button is-primary' %>
            </span>
            <span>
                <%= link_to "Delete",   post_path(@post), 
                                        method: :delete,
                                        data: {confirm: 'Are you sure?' },
                                        :class => 'button is-danger' %>
            </span>
        </p>
    </footer>
</div>

<hr>

<%= render 'comments/comments'%>
<%= render 'comments/form'%>